apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yammering-chimpanzee-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:4c9ec92b3fde41b2d5bad63bc7e8452c03ffb550@sha256:324a7bfb523866e57d78d9082af833c91e40b1578fcee8815512dc16fb146418
          name: container-image
